# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


reptile1 = Reptile.create(name: "Alligator Snapping Turtle", location: "Southeast", description: "The alligator snapping turtle can be found in rivers, lakes, backwater swamps, and periodically in brackish water systems.", image_link: 'https://news.illinois.edu/files/6367/578177/122614.jpg')
reptile2 = Reptile.create(name: "American Alligator", location: "Southeast", description: "Alligators are usually found in freshwater, slow-moving rivers. They also live in swamps, marshes and lakes.", image_link: 'https://c.pxhere.com/images/21/64/b3df74c410bfd562efc49b5ac83b-1594128.jpg!d')
reptile3 = Reptile.create(name: "American Crocodile", location: "Southeast", description: "They live in brackish or saltwater areas, and can be found in ponds, coves, and creeks in mangrove swamps.", image_link: 'https://c.pxhere.com/photos/39/3d/biscayne_national_park_florida_american_crocodile_wildlife_river_water_shoreline_dangerous-1355926.jpg!d')
reptile4 = Reptile.create(name: "Carolina Anole", location: "Southeast", description: "It can be found in swamps, forests, wooded beaches and other areas with trees. It may also be found in parks and yards.", image_link: 'https://c.pxhere.com/photos/b9/2b/nature_wildlife_brownanole_sonyalpha-170495.jpg!d')
reptile5 = Reptile.create(name: "Common Box Turtle", location: "Northeast", description: "Common Box Turtles can be found in dry regions occasionally, but they tend to thrive best in moist, forested areas with lots of brush.", image_link: 'https://c.pxhere.com/photos/77/00/tortoise_grass_animal_shell-505431.jpg!s2')
reptile6 = Reptile.create(name: "Chuckwalla", location: "Southwest", description: "Strictly a rock dweller, the chuckwalla is found in rocky outcrops, lava flows, and rocky hillsides of the Great Basin, Mohave and Sonoran deserts", image_link: 'https://c.pxhere.com/photos/87/37/chuckwalla_sauromalus_ater_reptile_animal_lizards_dragon_nature_lizard-539366.jpg!s2')
reptile7 = Reptile.create(name: "Garter Snake", location: "Northeast", description: "Some of the different ecosystems that they live in include wetlands, marshes, swamps, woodlands, grasslands, forests, and more. Many species also range into areas near human activity, like farms, pastures, parks, gardens, and more.", image_link: 'https://images.unsplash.com/photo-1588471627411-e60ce31e11f9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Z2FydGVyJTIwc25ha2V8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60')
reptile9 = Reptile.create(name: "Copperhead", location: "Northeast", description: "Copperheads live in a range of habitats, from terrestrial to semiaquatic, including rocky, forested hillsides and wetlands. ", image_link: 'https://cdn.mos.cms.futurecdn.net/U4LVbsR7zhEKTP6fegzxQW.jpg')
reptile10 =Reptile.create(name: "Cottonmouth", location: "Southeast", description: "They can be found in nearly all freshwater habitats but are most common in cypress swamps, river floodplains, and heavily-vegetated wetlands. Cottonmouths will venture overland and are sometimes found far from permanent water.", image_link: 'https://cdn.mos.cms.futurecdn.net/WHMgGuKrVv77sqXp64ETKT.jpg')
reptile11 =Reptile.create(name: "Diamondback Terrapin", location: "Northeast", description: "Diamondback terrapins live in the brackish water of salt marshes, estuaries, and tidal creeks.", image_link: 'https://portal.ct.gov/lib/deep/wildlife/images/outreach/fact_sheets/dbterrapin.jpg')
reptile12 =Reptile.create(name: "Eastern Coral Snake", location: "Southeast", description: "They live in the wooded, sandy, and marshy areas of the southeastern United States, and spend most of their lives burrowed underground or in leaf piles.", image_link: 'https://media.istockphoto.com/photos/coral-snake-picture-id453250621?k=20&m=453250621&s=612x612&w=0&h=oo6PxLl3AaB6w-VAziYmc_kLcpL8vdHkFM0G5fbXCg4=')
reptile13 =Reptile.create(name: "Gila Monster", location: "Southwest", description: "Gila monsters are desert dwellers, living near washes and arroyos and in semiarid rocky regions of desert scrub or grasslands. Gila monsters also seem to prefer rocky foothills and avoid open flats and agricultural areas.", image_link: 'https://animals.sandiegozoo.org/sites/default/files/2016-11/animals_hero_gila_monster_0.jpg')
reptile15 =Reptile.create(name: "Mojave Desert Tortoise", location: "Southwest", description: "Mojave population of desert tortoise lives in a variety of habitats from sandy flats to rocky foothills, including alluvial fans, washes and canyons.", image_link: 'https://animalia.us-east-1.linodeobjects.com/animals/photos/full/1.25x1/desert-tortoise-8.jpg')
reptile16 =Reptile.create(name: "Racer Snake", location: "Northwest", description: "They are most abundant in edge habitats such as forest edges, old fields, and wetland edges. They are also often found in moderately disturbed or agricultural habitats.", image_link: 'https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/116/2020/08/IMG_2389_S-500x347.jpg')
reptile17 =Reptile.create(name: "Ribbon Snake", location: "Northwest", description: "Ribbon snakes are typically found in aquatic and high-vegetation areas such as marshes, ponds, streams, and lakes. ", image_link: 'https://upload.wikimedia.org/wikipedia/commons/d/de/EasternRibbonSnake.jpg')
reptile18 =Reptile.create(name: "Slender Glass Lizard", location: "NorthEast", description: "Slender glass lizards are most common in sandy areas of the Coastal Plain.", image_link: 'https://herpsofnc.org/wp-content/uploads/2016/09/5691229643_973d48fd87_b.jpg')
reptile19 =Reptile.create(name: "Common Musk Turtle",  location: "Northeast", description: "The habitat of the common musk turtle includes any kind of permanent body of water, like shallow streams, ponds, rivers, or clear water lakes, and it is rare to find the turtle elsewhere. ", image_link: 'https://racinezoo.org/sites/default/files/Common-Musk-Turtle.png')
reptile20 =Reptile.create(name: "Texas Horned Lizard",  location: "Southwest", description: "They can be found in arid and semiarid habitats in open areas with sparse plant cover. Because horned lizards dig for hibernation, nesting and insulation purposes, they commonly are found in loose sand or loamy soils.", image_link: 'https://www.wildlifedepartment.com/sites/default/files/THL.jpg')
reptile21 =Reptile.create(name: "Western Banded Gecko", location: "Southwest", description: "The western banded gecko is found in open arid deserts and desert grassland, in canyons and on hillsides. It is usually associated with rocks or other shelters, but is also is found in sandy arroyos and dunes.", image_link: 'https://reptilesmagazine.com/wp-content/uploads/data-import/6fd47469/westernbandedgeckoshutterstock573841951.jpg')
reptile22 =Reptile.create(name: "Western Diamondback Rattlesnake", location: "Southwest", description: "This snake is considered a generalist, which means that it isn't too picky about its habitat. It can be found living in deserts, grassy plains, forests, rocky hillsides and areas along the coast.", image_link: 'https://www.gannett-cdn.com/presto/2019/03/15/PSAT/bda063ae-345a-4c43-b99d-0d9d7d97eb19-Western_Diamondback_Rattlesnake-2.JPG?crop=1023,575,x0,y17&width=1023&height=511&format=pjpg&auto=webp')

journal1 = Journal.create(title:"First Encounter", message:"Finally saw my first alligator snapping turtle!", date:"03/04/22", reptile_id: reptile1.id)
journal2 = Journal.create(title:"Florida Vist", message:"Visited the everglades and saw and alligator.", date:"03/10/22", reptile_id: reptile2.id)

wishlist1 = Wishlist.create(reptile_id: reptile4.id)
wishlist2 = Wishlist.create(reptile_id: reptile5.id)
wishlist3 = Wishlist.create(reptile_id: reptile6.id)